version: '3.4'

services:
  customerdb:
    image: postgres

  registerserviceswithreflection:
    image: ${DOCKER_REGISTRY-}registerserviceswithreflection
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  postgres_data:


